// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHi1J6C2BTDO6dKt2X5dk4yLDeM0lOMdA',
    appId: '1:877030615042:web:b739770b2b1878151bdf1b',
    messagingSenderId: '877030615042',
    projectId: 'xpdf-dfba1',
    authDomain: 'xpdf-dfba1.firebaseapp.com',
    storageBucket: 'xpdf-dfba1.appspot.com',
    measurementId: 'G-54JMRXSBNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1fNGhQnIW_FXzom8VSGdvjd8-Xd74U7g',
    appId: '1:877030615042:android:3babdd01e859fc7b1bdf1b',
    messagingSenderId: '877030615042',
    projectId: 'xpdf-dfba1',
    storageBucket: 'xpdf-dfba1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnecHy4tGuw23x3l6fGv16x8nfUNINmOM',
    appId: '1:877030615042:ios:77996c11d077bd021bdf1b',
    messagingSenderId: '877030615042',
    projectId: 'xpdf-dfba1',
    storageBucket: 'xpdf-dfba1.appspot.com',
    iosBundleId: 'com.example.xpdf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnecHy4tGuw23x3l6fGv16x8nfUNINmOM',
    appId: '1:877030615042:ios:899498810d82c99a1bdf1b',
    messagingSenderId: '877030615042',
    projectId: 'xpdf-dfba1',
    storageBucket: 'xpdf-dfba1.appspot.com',
    iosBundleId: 'com.example.xpdf.RunnerTests',
  );
}
